<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <UsingTask TaskName="WriteGeneratedCode" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup>
      <FilePath ParameterType="System.String" Required="true" />
      <Namespace ParameterType="System.String" Required="true" />
      <Message ParameterType="System.String" Required="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs"><![CDATA[
var code = $@"namespace {Namespace}
{{
    public static class BuildInfo {{ public const string Message = ""{Message}""; }}
}}
";
System.IO.File.WriteAllText(FilePath, code);
]]></Code>
    </Task>
  </UsingTask>


  <Target Name="GenerateBuildInfo" BeforeTargets="BeforeBuild">
    <PropertyGroup>
      <_GeneratedCodeDir>$(IntermediateOutputPath)Generated\</_GeneratedCodeDir>
      <_GeneratedFilePath>$(_GeneratedCodeDir)GeneratedInfo.cs</_GeneratedFilePath>
    </PropertyGroup>

    <MakeDir Directories="$(_GeneratedCodeDir)" />
    <WriteGeneratedCode
      FilePath="$(_GeneratedFilePath)"
      Namespace="WrongTiming.Generated"
      Message="Generated before build" />

    <ItemGroup>
      <Compile Include="$(_GeneratedFilePath)" />
      <FileWrites Include="$(_GeneratedFilePath)" />
    </ItemGroup>
  </Target>

</Project>
