<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App1\App1.csproj" />
    <ProjectReference Include="..\App2\App2.csproj" />
    <ProjectReference Include="..\App3\App3.csproj" />
    <ProjectReference Include="..\App4\App4.csproj" />
  </ItemGroup>
</Project>
