<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <BuildTasksToolPath>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../BuildTasks/bin/$(Configuration)/net8.0/BuildTasks.dll'))</BuildTasksToolPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildTasks\BuildTasks.csproj" />
  </ItemGroup>

  <Target Name="GenerateBuildManifest"
          BeforeTargets="CoreCompile"
          DependsOnTargets="ResolveProjectReferences">
    <Exec Command="dotnet &quot;$(BuildTasksToolPath)&quot; &quot;$(IntermediateOutputPath)gateway.manifest&quot;" />
  </Target>

</Project>
