<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>$(DefineConstants);ENABLE_LOGGING</DefineConstants>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)local.overrides.props"
          Condition="Exists('$(MSBuildThisFileDirectory)local.overrides.props')" />
</Project>
